import{useState,useMemo,useEffect}from'react';import{MediaItem,MediaType,SortOption}from'./types';import{useDataTable}from'../../../hooks/useDataTable';
const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');const opts:RequestInit={credentials:'include'};
export function useMedia(){const[media,setMedia]=useState<MediaItem[]>([]);const[currentFolderId,setCurrentFolderId]=useState<string|null>(null);const[filterType,setFilterType]=useState<MediaType|'all'>('all');const[linkFilter,setLinkFilter]=useState<'all'|'linked'|'unlinked'>('all');const[sortBy,setSortBy]=useState<SortOption>('newest');const[viewMode,setViewMode]=useState<'grid'|'list'>('grid');const[selectedIds,setSelectedIds]=useState<string[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{fetch(`${API}/api/media`,opts).then(async r=>{if(!r.ok)throw new Error(`Media API returned ${r.status}`);const b=await r.json();setMedia(Array.isArray(b)?b:[]) }).catch(()=>setMedia([])).finally(()=>setLoading(false))},[]);
 const currentFolder=useMemo(()=>currentFolderId?media.find(x=>x.id===currentFolderId)||null:null,[currentFolderId,media]);const breadcrumbs=useMemo(()=>{const out:MediaItem[]=[];let id=currentFolderId;while(id){const f=media.find(x=>x.id===id);if(!f)break;out.unshift(f);id=f.parentId||null}return out},[currentFolderId,media]);
 const filterFn=(i:MediaItem)=>i.parentId===currentFolderId&&(filterType==='all'||i.type===filterType)&&(linkFilter==='all'||i.type==='folder'||(linkFilter==='linked'?!!i.linkedTo?.length:!i.linkedTo?.length));
 const comparator=(a:MediaItem,b:MediaItem,s:any,d:any)=>{if(a.type==='folder'&&b.type!=='folder')return-1;if(a.type!=='folder'&&b.type==='folder')return 1;if(s==='createdAt'||s==='size'){const av=s==='createdAt'?new Date(a.createdAt).getTime():a.size||0;const bv=s==='createdAt'?new Date(b.createdAt).getTime():b.size||0;return d==='asc'?av-bv:bv-av}if(s==='name')return d==='asc'?a.name.localeCompare(b.name):b.name.localeCompare(a.name);return 0};
 const table=useDataTable<MediaItem>({data:media,searchFields:['name'],filterFn,customComparator:comparator});const storageStats=useMemo(()=>{const x={totalSize:0,imageSize:0,videoSize:0,docSize:0,audioSize:0,maxSize:100*1024*1024*1024};media.forEach(i=>{x.totalSize+=(i.size||0);if(i.type==='image')x.imageSize+=i.size||0;if(i.type==='video')x.videoSize+=i.size||0;if(i.type==='document')x.docSize+=i.size||0;if(i.type==='audio')x.audioSize+=i.size||0});return x},[media]);
 const createFolder=async(name:string,color?:string)=>{const r=await fetch(`${API}/api/media/folders`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,parentId:currentFolderId,folderColor:color||'#FF0000'})});if(!r.ok)throw new Error('Unable to create folder');setMedia(p=>[...(p),await r.json()])};
 const deleteItem=async(id:string)=>{await fetch(`${API}/api/media/${id}`,{method:'DELETE',...opts});setMedia(p=>p.filter(x=>x.id!==id));setSelectedIds(p=>p.filter(x=>x!==id))};const updateItem=async(id:string,u:Partial<MediaItem>)=>{const r=await fetch(`${API}/api/media/${id}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(u)});if(!r.ok)throw new Error('Unable to update media');const b=await r.json();setMedia(p=>p.map(x=>x.id===id?{...x,...b}:x))};const bulkDelete=async()=>{await Promise.all(selectedIds.map(id=>deleteItem(id)));setSelectedIds([])};const bulkMove=async(target:string|null)=>{await Promise.all(selectedIds.map(id=>updateItem(id,{parentId:target})));setSelectedIds([])};const toggleSelect=(id:string)=>setSelectedIds(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);const selectAll=()=>setSelectedIds(table.filteredData.length===selectedIds.length?[]:table.filteredData.map(x=>x.id));return{media,currentFolderId,currentFolder,breadcrumbs,filteredMedia:table.filteredData,searchQuery:table.searchQuery,setSearchQuery:table.setSearchQuery,filterType,setFilterType,linkFilter,setLinkFilter,sortBy,setSortBy:(x:SortOption)=>{setSortBy(x);table.setSortField(null)},viewMode,setViewMode,selectedIds,toggleSelect,selectAll,clearSelection:()=>setSelectedIds([]),bulkDelete,bulkMove,navigateToFolder:(id:string|null)=>{setCurrentFolderId(id);table.setSearchQuery('');setSelectedIds([])},deleteItem,updateItem,addItem:(x:MediaItem)=>setMedia(p=>[x,...p]),createFolder,storageStats,sortField:table.sortField,sortDirection:table.sortDirection,handleSort:table.handleSort,isLoading:loading,setIsLoading:setLoading};}
