import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';
import { Post } from './types';
const API_BASE = (import.meta.env.VITE_API_URL || (import.meta.env.DEV ? 'http://localhost:5000' : '')).replace(/\/$/, '');
const request = async (path:string, options:RequestInit={}) => { const r=await fetch(`${API_BASE}${path}`,{...options,credentials:'include'}); const body=await r.json().catch(()=>({})); if(!r.ok) throw new Error(body.message||body.error||`Request failed (${r.status})`); return body; };
interface PostContextType { posts:Post[]; addPost:(post:Omit<Post,'id'|'views'|'shares'|'date'|'time'>&{date?:string;time?:string})=>Promise<Post>; deletePost:(id:string)=>Promise<void>; updatePost:(id:string,updates:Partial<Post>)=>Promise<void>; getPost:(id:string)=>Post|undefined; loading:boolean; error:string|null; }
const PostContext=createContext<PostContextType|undefined>(undefined);
export function PostProvider({children}:{children:ReactNode}){const [posts,setPosts]=useState<Post[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
  useEffect(()=>{request('/api/articles').then(data=>{const rows=Array.isArray(data)?data:data.articles||[];setPosts(rows.map((item:any)=>({id:String(item.id),title:item.title||'Untitled',status:item.status||'draft',author:item.author||'',category:item.category||'',date:item.date||'',time:item.time||'',views:item.views??'0',shares:item.shares??'0',image:item.image||item.image_url||'',isEdited:Boolean(item.isEdited),editDate:item.editDate,editTime:item.editTime,locationId:item.locationId||item.location_id,language:item.language||'en'})))}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  const addPost=async(data:any)=>{const created=await request('/api/articles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const item=created.article||created;const post:any={...data,id:String(item.id),views:item.views??'0',shares:item.shares??'0',date:item.date||data.date||'',time:item.time||data.time||''};setPosts(p=>[post,...p]);return post;};
  const deletePost=async(id:string)=>{await request(`/api/articles/${id}`,{method:'DELETE'});setPosts(p=>p.filter(x=>x.id!==id));};
  const updatePost=async(id:string,updates:Partial<Post>)=>{const updated=await request(`/api/articles/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(updates)});const item=updated.article||updated;setPosts(p=>p.map(x=>x.id===id?{...x,...updates,...item,id}:x));};
  const getPost=(id:string)=>posts.find(p=>p.id===id); return <PostContext.Provider value={{posts,addPost,deletePost,updatePost,getPost,loading,error}}>{children}</PostContext.Provider>;}
export function usePostContext(){const c=useContext(PostContext);if(!c)throw new Error('usePostContext must be used within PostProvider');return c;}
